# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# General
# ---------------------------
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^.vscode:'
      - '^test:'
      - '^docs:'

# ---------------------------
# Publishers
# ---------------------------
# publishers:
#  - name: "Publish GoDocs"
#    cmd: make godocs

# ---------------------------
# Github Release
# ---------------------------
release:
  prerelease: true
  name_template: "Release v{{.Version}}"

